### ISSUE TITLE
Add per-host configuration

### ISSUE THREAD

**Issue by nirvdrum** [nevans/resque-pool#1]
In a cluster of workers, I usually want different workers handling different queues.  It'd be nice if in addition to splitting by environment that I could split by hostname in that environment.

**Comment by nevans** [comment]
This can be handled via the new [custom config loader](https://github.com/nevans/resque-pool#custom-configuration-loader) in `0.6.0`.  I'm closing this ticket, but I'll gladly review a pull request for an optional config loader that allows per-host config from a file.
