### ISSUE TITLE
resque-pool doesn't properly pass RUN_AT_EXIT_HOOKS env variable to workers

### ISSUE THREAD

**Issue by wollkind** [nevans/resque-pool#106]
The base resque system has the option of using ENV['RUN_AT_EXIT_HOOKS'] to each worker in the resque:work task.  resque-pool does not seem to pass this along, and for whatever reason the default value is false, meaning that at_exit doesn't work for a job running under resque-pool.  

Seems that
      worker.run_at_exit_hooks = ENV['RUN_AT_EXIT_HOOKS']
should be added to create_worker in pool.rb.

Possibly other env variable passthroughs from the resque:work task should be added here as well, but I don't know.

**Comment by nevans** [comment]
Merged #114 (with an additional change to ensure it still works pre-resque 1.24).  Let me know if `master` or `0.5.0.rc1` work for you.
