### ISSUE TITLE
Add License information to Gemspec

### ISSUE THREAD

**Issue by coreyhaines** [nevans/resque-pool#110]
This will make it show up on rubygems.org. I'm doing due diligence on our gems and need to find out the licenses for all the gems. Having it show up on rubygems.org cuts out the step of having to go to the github repo.

**Comment by nevans** [comment]
It's in [the latest release candidate](https://rubygems.org/gems/resque-pool/versions/0.4.0.rc3), but *not* in the latest stable release.  Of course, it's *absurd* that I haven't released a new stable gem in over two years (even though I've been using the RCs in production for the entire time).  Sorry!  That RC will be promoted to stable within a week.
