### ISSUE TITLE
Silent crash

### ISSUE THREAD

**Issue by letronje** [nevans/resque-pool#112]
What would be a good way to debug silent crashes with the resque-pool master process and the resque workers ?

Is there a way to enable auto restart ?

**Comment by nevans** [comment]
*(Sorry for taking so long to respond to this!)*

First debugging step would be to run resque-pool non-daemonized from the console and see what it logs to stderr/stdout.  Second step: enable verbose logging (set the `VERBOSE` and `VVERBOSE` env vars).    Check the logfiles if it's daemonized.  Were you able to solve your problem?

If the pool master fails to start up for anything other than a config error or if it crashes, that's a bug in resque-pool (please report it).  Auto-restart is outside the scope of resque-pool and is better handled by your process monitor or init system (upstard, systemd, bluepill, god, docker, whatever).
