### ISSUE TITLE
bin/resque-pool will default to RAILS_ENV=test in Rails 4

### ISSUE THREAD

**Issue by gabetax** [nevans/resque-pool#113]
If you run bin/resque-pool without setting RAILS_ENV, it will default to "test". This can be problematic if you're changing your redis connection depending on the environment.

The cause of this is the [test_unit railtie](https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/railtie.rb#L1-L2), which sets the RAILS_ENV=test when running `rake default` or `rake test`. Normally this code doesn't get triggered since either rake isn't required by Rails by default, or because the 'rake' command line script will set the `Rake.application.top_level_tasks` appropriately. However, [`Resque::Pool::CLI#start_pool`](https://github.com/nevans/resque-pool/blob/master/lib/resque/pool/cli.rb#L127-L131) requires rake first (which sets `Rake.application.top_level_tasks` to "default"), and then when the app's Rakefile requires config/application, the logic is triggered.

Possible solutions:
- resque-pool attempts to require config/application, if it exists, before requiring rake
- resque-pool CLI either requires an environment or explicitly defaults to 'development' if not set
- sub-class Rake::Application to set `default_task_name` to 'rescue:pool'

**Comment by istana** [comment]
thanks for this, still present

**Comment by brucek** [comment]
FYI I have a fix for this in #160, just not merged yet :-/

FWIW this uses option # 3 (sub-class Rake::Application to set default_task_name to 'resque:pool')

**Comment by nevans** [comment]
FYI: #160 was merged and released with 0.7.0 (2019-03-08), but I never got around to cleaning up old issues.
