### ISSUE TITLE
Cannot run under docker because PID of pool manager is 1

### ISSUE THREAD

**Issue by nevans** [nevans/resque-pool#116]
Need to update `Resque::Pool::PooledWorker` to be smarter about what the manager PID is (can't just check for `ppid != 1`)

**Comment by jkrall** [comment]
+1 ... just ran into this as well, was *really* hard to track down until I randomly came across this issue.

**Comment by artygus** [comment]
:+1:

**Comment by nevans** [comment]
This interacts poorly with `resque-multi-job-forks` as currently implemented.  Will need to work on another fix.

**Comment by nevans** [comment]
with the following processes (e.g. pool of only one worker, under docker so we get PID 1):

    PID: 1 (resque-pool manager)
    PID: 2 (resque worker parent)
    PID: 3 (resque worker child)

Normally, shutdown? is only called by the resque worker parent.  But `resque-multi-job-forks` hijacks the child and lets it stick around for a while, behaving as if it were a "can't fork" worker parent until it hits one of its limits.  That means that `shutdown?` will be called by both the worker parent *and* by the worker child and it needs to work in both cases.

My proposed solution: instead of storing a single PID (e.g. 1, in the example above) for the pool manager, we'll store two PIDs (1,2).  In the normal case, storing that extra PID won't make any difference (it will be the PID of the current process).

**Comment by nevans** [comment]
see 2f91e91, testing this out now (will push rc4 if it works).

**Comment by nevans** [comment]
2f91e91 fixed it.  I pushed that as `0.5.0.rc1`
