### ISSUE TITLE
Redis Connection Pool recommendation

### ISSUE THREAD

**Issue by dsshap** [nevans/resque-pool#117]
Can I get some recommendations on what to use for managing a redis connection pool when using resque-pool?

I have a lot of workers firing and establishing new connections each time which is causing me to see 

"ERROR: Redis::TimeoutError: Connection timed out"

**Comment by nevans** [comment]
@dsshap The [README](https://github.com/nevans/resque-pool#rake-task-config) has been updated with the recommendation for when you have redis connections other than Resque.  Putting `Resque.redis.client.reconnect` or `$redis.client.reconnect` (depending on where youre redis connection lives) into the `after_prefork` hook should fix it for you.

I might be misunderstanding your problem.  If so, please reopen this issue and clarify.

**Comment by Jonnymcc** [comment]
@dsshap Did you ever resolve this? We have millions of jobs that on average last about one second, and when they all get queued up at once, our dedicated Redis backend for Resque gets hit with over 50k new connections per minute. I've tried adding the reconnect from the README but it seemed to have no affect.

**Comment by dsshap** [comment]
@Jonnymcc we ended up using sidekiq instead of resque.

This was a very long time ago, I don't recall if we patched this in any way.
