### ISSUE TITLE
Child process memory keeps growing

### ISSUE THREAD

**Issue by phuongnd08** [nevans/resque-pool#136]
I was observing the behavior of resque-pool on a Mac.
We have resque pool forking 5 child processes doing nothing.
Right after successful forking, the parent resque-pool process took 120M and each child resque process took less than 20M. But after 5 minutes, memory start growing up to 110M per child resque process even though they were not doing anything. This led to aggressive memory usage in Heroku causing memory to keep getting swapped out to disk. Could you recommend a solution? I'm looking for a way to figure out the reason why *idle* child process keeps eating memory as well as a way to kill and refork them if memory has been grown too much.

**Comment by clintmod** [comment]
@phuongnd08 did you solve this? I'm seeing the same thing.

**Comment by phuongnd08** [comment]
What I did is to use dynamic loader to periodically kill the child process to prevent that.
