### ISSUE TITLE
No ActiveRecord pool connection

### ISSUE THREAD

**Issue by patrykwojtynski** [nevans/resque-pool#152]
Hi, I'm trying to add resque-pool to my Rails app but I can't establish ActiveRecord connection.
Stack:
Resque: 1.22.0
Resque-pool: 0.6.0
Ruby: 2.3.0
Rails: 4.0.13
Postgres

resque.rake
```
require 'resque/tasks'
require 'resque/pool/tasks'
require 'resque/scheduler/tasks'

task "resque:setup" => :environment do
  require 'resque/failure/multiple'
  require 'resque/failure/redis'
  require 'resque/rollbar'

  Resque::Failure::Multiple.classes = [Resque::Failure::Redis, Resque::Failure::Rollbar]
  Resque::Failure.backend = Resque::Failure::Multiple
end

task "resque:pool:setup" => :environment do
  # close any sockets or files in pool manager
  ActiveRecord::Base.connection.disconnect!

  Resque::Pool.after_prefork do
    ActiveRecord::Base.establish_connection
    Resque.redis.client.reconnect
  end
end
```

initializers/resque.rb
```
require 'resque/scheduler'
require 'resque/scheduler/server'
#setup resque
ENV["REDISTOGO_URL"] ||= "redis://localhost:6379/"

uri = URI.parse(ENV["REDISTOGO_URL"])
Resque.redis = Redis.new(:host => uri.host, :port => uri.port, :password => uri.password)
```

I'm starting all with `RAILS_ENV=development rake resque:pool`

The problem is when I'm trying to use ActiveRecord inside jobs (finders are throwing ActiveRecord::RecordNotFound for existing rows)  and `puts ActiveRecord::Base.connection_pool.connected?` always return `false`.

Someone faced the same issue?

**Comment by qingmulanyun** [comment]
Have you fixed this issue?  I cannot find any active_record in my worker. e.g. User.all.count always equals zero..
