### ISSUE TITLE
How does resque-pool compare to resque:workers

### ISSUE THREAD

**Issue by dimasusername** [nevans/resque-pool#166]
resque:workers can fork however many workers you set in COUNT env variable. Does this mean the resque-pool gem isn't required anymore? Or does it provide some better management?

**Comment by nevans** [comment]
resque-pool can preload the environment in the parent, which can cut down on memory usage and start-up time. It will monitor children, restarting them if they crash, relaying signals to all of them, etc. It can also manage multiple queue configurations, and can dynamically adjust configuration at runtime.

I hope functionality like this will eventually be incorporated into the main `resque` gem, but I think the `COUNT` env var was already in there when I first wrote `resque-pool`, back in 2010!
