### ISSUE TITLE
Release a version supporting Resque 2.0

### ISSUE THREAD

**Issue by jesperronn** [nevans/resque-pool#173]
Issue #170 and the fix in #171 now allows this project to be used with Rescue 2.0

However, we need somebody who can:

* [ ] tag the new release in Github
* [ ] Update the changelog
* [ ] Upload new release to rubygems.org

Who can help with that?

PS what is the proper version number for that? `v1.0.0`?

**Comment by jesperronn** [comment]
This may be relevant to maintainers or previous maintainers, for instance @nevans

**Comment by nevans** [comment]
Hi all, sorry for being MIA for so long. Can you try out v0.7.0 (just released)? Let me know how it works for you! Thanks!

**Comment by jesperronn** [comment]
Works for me, thanks for creating the releas @nevans
