### ISSUE TITLE
Why forbid rake 13.0?

### ISSUE THREAD

**Issue by jrochkind** [nevans/resque-pool#184]
The gemspec says `spec.add_dependency "rake",   ">= 10.0", "< 13.0"`

https://github.com/nevans/resque-pool/blob/master/resque-pool.gemspec#L33

This means if a project has `resque-pool` in it's gemfile, it is prevented from working with latest rake 13. 

Is this intentional? Accidental?  Rake is kind of weird, I wonder if rake should be in the gemspec at all. 

It looks like the only [backwards incompat listed for rake 13](https://github.com/ruby/rake/blob/master/History.rdoc#1300) is dropping support for MRI versions less than 2.2; so there's probably no reason not to allow at least rake 13 (along with older versions as current). I will PR.

**Comment by jrochkind** [comment]
[Here's the commit](https://github.com/nevans/resque-pool/commit/5617ab57372565fadc4375084ce634cccd1cb0ad) where the `< 13` requirement was added; prior to that, the `rake` dependency had no upper bound. 

I think it may make sense to give it no upper bound again (but maybe still `>= 10`) so a new resque-pool release doensn't have to be made every time there's a new rake major release. 

On the other hand, this would open up risk that a rake major release could break resque-pool, I guess. Although that seems relatively unlikely, resque-pool uses public rake API that is unlikely (although not impossible) to change. 

Thoughts?

**Comment by nevans** [comment]
Sorry for taking so long to get around to merging #183 and releasing v0.7.1.  I sometimes missed the github notifications.

I'm not sure whether I prefer with or without an upper bound, but `bundler gem` recommended adding the upper bound, so I took their advice! :)
