### ISSUE TITLE
Is there a way to determine the available cores and determine number of threads based on cpu cores?

### ISSUE THREAD

**Issue by x9sim9** [nevans/resque-pool#198]
Title explains it but I have multiple environments with different hardware and so want to assign threads based on the number of cpu cores each machine has,

thanks,
Simon

**Comment by nevans** [comment]
There's nothing built-in, but you should be able to create a [Custom Config Loader](https://github.com/nevans/resque-pool#custom-configuration-loader) which handles that for you.  And you should be able to base it off of ruby stdlib's [Etc.nprocessors](https://ruby-doc.org/stdlib-2.7.3/libdoc/etc/rdoc/Etc.html#method-c-nprocessors).  I hope that helps. 🙂

**Comment by nevans** [comment]
If you get this working for you, I'll gladly merge a README example.
