### ISSUE TITLE
Sending HUP does not reopen log files

### ISSUE THREAD

**Issue by tekin** [nevans/resque-pool#30]
Currently using logrotate to rotate the log files for resque-pool but sending HUP does reopen the log files - instead the manager keeps logging to the renamed log file, in this case resque.log.1.

**Comment by PatrickTulskie** [comment]
Interesting that this is still open from 2011.  I had a bunch of servers running resque-pool that kept running out of disk space even though logrotate is sending a HUP to the masters after rotate.

I was going through the differences between what HUP does vs what I expected it to do and I realized that all resque-pool is re-opening $stdout and $stderr.  If you have additional loggers inside of your application they will never get re-opened.

I went into Unicorn and looked through what they are doing there and apparently it loops through the ObjectSpace and looks for open files that are in append/write-only mode and re-opens those.  I think this is probably a better solution.

Has anyone attempted to do something similar in resque-pool?  I am about to take a run at doing something similar to Unicorn's logrotate approach so I can try that out in production.

@tekin Did you ever get this resolved some other way?

**Comment by nevans** [comment]
My gut instinct is that running through ObjectSpace and managing everyone else's append files is both overkill and dangerous.  I'd rather just be responsible with my own logfiles and let other software handle their own (e.g. register additional HUP trap to manage the rest).

BUT... if Unicorn is doing it, then it must be a good idea *and* work well for a bunch of people.  I trust Eric Wong's unix-fu.  Send in a PR that (very) closely mirrors unicorn's code and I'll probably merge it.

**Comment by nevans** [comment]
Merged to `master` now.  Next rc gem push (0.6.0.rc1?) should include this.  Thanks @PatrickTulskie!

**Comment by PatrickTulskie** [comment]
Awesome. Glad I could help!
