### ISSUE TITLE
Resque Pool 0.4.0

### ISSUE THREAD

**Issue by schneems** [nevans/resque-pool#87]
Do you have a list of blockers or issues for this release? I'm writing an article on using resque-pool with heroku and would love to be able to use ERB in my YAML files (looks like a feature of 4.0.0 only).

Thanks for this library btw, it was easy to set up and did exactly what I expected it to do :heart:

**Comment by nevans** [comment]
FYI: I *finally* released 0.4.0 with the changes your article referenced.  I also released 0.5.0-rc1 with some other heroku/TERM_CHILD related changes (which I haven't tested on heroku myself yet).  Thanks!
